-- SQL pour créer la table survey_data dans Supabase

-- Créer la table
CREATE TABLE IF NOT EXISTS survey_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre TEXT,
    filiere TEXT,
    heures INTEGER,
    outils_numeriques TEXT,
    note FLOAT,
    sport TEXT,
    conseil TEXT,
    isReal INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Ajouter des index pour améliorer les performances
CREATE INDEX IF NOT EXISTS idx_survey_data_created_at ON survey_data(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_survey_data_genre ON survey_data(genre);
CREATE INDEX IF NOT EXISTS idx_survey_data_filiere ON survey_data(filiere);

-- Activer RLS (Row Level Security)
ALTER TABLE survey_data ENABLE ROW LEVEL SECURITY;

-- Politique pour permettre la lecture publique
CREATE POLICY "Allow public read access" ON survey_data
    FOR SELECT USING (true);

-- Politique pour permettre l'insertion publique
CREATE POLICY "Allow public insert access" ON survey_data
    FOR INSERT WITH CHECK (true);

-- Vérifier que la table a bien été créée
SELECT * FROM survey_data LIMIT 1;
